# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main  # <--- alterado para main (ajuste se necessário)

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Docker Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # <-- ajuste aqui se necessário
        tags: |
          $(tag)

- stage: Deploy
  displayName: Simulated Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Fake deploy job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Simulando deploy para ambiente de staging..."
        echo "Imagem com tag $(tag) pronta para ser usada!"
      displayName: "Simulate Deploy Step"
